name: Wake Up Streamlit App

on:
  schedule:
    # Chạy mỗi 2 tiếng một lần (0, 2, 4, 6... giờ UTC)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Cho phép bạn nhấn nút chạy thử thủ công

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run wake up script
        run: python wake_up.py
