name: Wake Up Streamlit App

on:
  schedule:
    # Chạy mỗi 2 tiếng một lần
    - cron: '0 */2 * * *'
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Đã cập nhật từ v3 lên v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Đã cập nhật từ v4 lên v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run wake up script
        run: python wake_up.py
