name: Wake Up Streamlit App

on:
  schedule:
    # Chạy tự động mỗi 2 tiếng (0h, 2h, 4h,...) theo giờ UTC
    - cron: '0 */2 * * *'
  workflow_dispatch: 
    # Cho phép bạn bấm nút "Run workflow" để chạy thử bất cứ lúc nào

jobs:
  ping_app:
    runs-on: ubuntu-latest
    
    # Ép hệ thống sử dụng môi trường thực thi mới để xóa cảnh báo Node.js 20
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run wake up script
        run: python wake_up.py
